from django.db import models


class Category(models.Model):
    """
    Represents a category under which recipes
    are grouped.
    Relation: Each recipe has one Category

    Warning: Deleting a category will delete
    all recipes within it.
    """

    # Not creating category_id as a default id field will be generated by Django
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"
