# Generated by Django 5.1.3 on 2025-03-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="user_id",
        ),
    ]
