# Generated by Django 5.1.3 on 2025-03-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_recipe_category_id_remove_recipe_user_id"),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipe.recipe"
            ),
        ),
        migrations.RemoveField(
            model_name="savedrecipe",
            name="recipe_id",
        ),
        migrations.RemoveField(
            model_name="savedrecipe",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="SavedRecipe",
        ),
    ]
