# Generated by Django 5.1.3 on 2025-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
