# Generated by Django 5.1.3 on 2025-03-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_userprofile_delete_rating"),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedrecipe",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="savedrecipe",
            name="user_id",
        ),
        migrations.AddField(
            model_name="recipe",
            name="user_profile",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField(default=0)),
                (
                    "recipe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipe.recipe"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
        ),
    ]
