# Generated by Django 5.1.3 on 2025-03-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_rename_recipe_id_savedrecipe_recipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="recipe_id",
            new_name="recipe",
        ),
    ]
